services:
  - type: web
    name: task-management-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8081
      - key: DB_URL
        fromDatabase:
          name: task-management-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: task-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: task-management-db
          property: password
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: task-management-db
    databaseName: postgres
    region: singapore
