services:
  - type: web
    name: task-management-backend
    env: docker
    branch: task-management-app-backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8081
      - key: DB_URL
        value: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require
      - key: DB_USER
        value: postgres.nhhsepxupufeugvnzqtf
      - key: DB_PASSWORD
        value: Root@8010166
      - key: JWT_SECRET
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A47
