spring.application.name=task-mgmt-app
server.port=${PORT:8081}
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.username=${DB_USER:postgres.nhhsepxupufeugvnzqtf}
spring.datasource.password=${DB_PASSWORD:Root@8010166}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
